### ISSUE TITLE
Funksiyani ishlatish

### ISSUE THREAD

**Issue by omon490** [Abdullayev99/youtube_demo#1]
Tepada tayyor funksiya bor edi lekin undan foydalangan holda yozish mumkun edi

**Comment by omon490** [comment]
![image](https://user-images.githubusercontent.com/71442262/103484657-5eb17c80-4e12-11eb-97a3-3aeb303e0fbc.png)

**Comment by Abdullayev99** [comment]
yes brother 😊I really missed it, and  thank you for the comment.
